python3 readTest.py &
python3 readTest.py &
python3 readTest.py &
python3 readTest.py &
python3 readTest.py &
python3 readTest.py &
python3 readTest.py &
python3 readTest.py &
python3 readTest.py &
python3 readTest.py &
